### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ichavez** [jacobm001/dbt-mssql#1]
Hi Jacob!

I would like to work on an Azure SQL Data Warehouse plugin and start from where you are using the pyodbc module.

Would you mind adding a license file so we can get started and publish ours ?
Something like: https://github.com/fishtown-analytics/dbt-spark/blob/master/License.md 

Thanks,

Isaac

**Comment by jacobm001** [comment]
Issac,
I have added the same license that dbt itself is released with. Sorry for the delay!
