### ISSUE TITLE
Link to this in the dbt documentation

### ISSUE THREAD

**Issue by drewbanin** [jacobm001/dbt-mssql#2]
Hey @jacobm001! Nice work on this plugin!!

If you'd like, I'd be very happy to include a link to this repo in the dbt docs site. I'd like to include it under "Supported databases":

<img width="282" alt="Screen Shot 2019-08-02 at 12 05 21 PM" src="https://user-images.githubusercontent.com/1541139/62383473-dc869f80-b51d-11e9-905c-dfb27850b06f.png">

If that sounds alright to you, I can get this up on the site today :)

Couple of quick things:
 - Any plans / interest in putting this on pypi?
 - I can label this "Beta" and "Community Supported" -- we'll link back to the repo here, and PyPi if/when that's set up
 - I know that building a plugin is no small feat - please don't hesitate to let us know if we can ever be helpful in reviewing code / helping with upgrade the version of dbt-core / improving the adapter interface / etc.

Thanks!

**Comment by jacobm001** [comment]
@drewbanin: Yes, that'd be great! I've currently released it on PyPi under the name _dbt-mssql_. I think both labels would be prudent.
