### ISSUE TITLE
Exclude password in _connection_keys

### ISSUE THREAD

**Issue by drewbanin** [jacobm001/dbt-mssql#3]
The [_connection_keys](https://github.com/jacobm001/dbt-mssql/blob/ed56bcb3e69368df8ff0cb29a966d619fa2166b5/dbt/adapters/mssql/connections.py#L62) method currently returns a list of keys including `PWD`. This list of keys is used to filter the information displayed by the `dbt debug` command. It's probably a good idea to remove the `PWD` field from this list, as it's likely undesirable to print out the password field in plaintext on the terminal.

**Comment by jacobm001** [comment]
Fixed.
