### ISSUE TITLE
Documentation note about making sure 'ODBC Driver 17 for SQL Server' is installed on local machine

### ISSUE THREAD

**Issue by curious-bryan** [jacobm001/dbt-mssql#5]
@jacobm001 thank you for developing this dbt database adapter for MSSQL!  Fantastic contribution!

It may be helpful to some newbie dbt users to have a reminder like:

> Remember to check that 'ODBC Driver 17 for SQL Server' is installed on your local machine.  

I had this issue. 🤦‍♂ 

If you agree, here are some links.  
If you disagree, I totally understand.  It is not your job to remind others of the basics. 

> - **How to check:** https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/check-the-odbc-sql-server-driver-version-windows?view=sql-server-2017
> - **Where to download:** https://www.microsoft.com/en-us/download/details.aspx?id=56567

**Comment by jacobm001** [comment]
@curious-bryan: I've added some details into the readme to address this confusion. I think that should cover it.

**Comment by curious-bryan** [comment]
@jacobm001 Nice!  Well said!
